spring.application.name=MySpringBoot

server.port=8080

# program argument
myboot.name=MySpring
myboot.age=${random.int(1,100)}
myboot.fullName=${myboot.name} Boot

# 현재 활성화된 Profile 값 설정 test/prod
spring.profiles.active=prod

# actuator
management.endpoints.web.exposure.include=*

spring.boot.admin.client.url=http://localhost:8090